version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.15.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            go test
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

# Invoke jobs via workflows
workflows:
  functional:
    jobs:
      - build
